db:
  provider:           redis
  action:             save
  db:                 0
  id:                 $id
  key:                DEFAULT_KEY

forward:
  tap: false

tap:
  tap: true
  
get:
  method:             get
  follow:             5
  rejectUnauthorized: false
  compressed:         true
  parse:              false
  timeout:            0
  limit:              100

placeholders:
  url:         example.com
  
xml2json:
  object:        true
  reversible:    false
  coerce:        false
  sanitize:      true
  trim:          true
  arrayNotation: false
