db:
  provider:           $db
  action:             save
  db:                 0
  id:                 $id
  key:                DEFAULT_KEY

forward:
  tap: false

tap:
  tap: true
  
get:
  # headers:
  accept:             '*/*'
  compressed:         true

  method:             get
  follow:             20
  follow_set_cookies: true
  follow_set_referer: true
  follow_keep_method: true

  rejectUnauthorized: false
  parse:              true
  timeout:            0
  url:                $url

placeholders:
  url:         example.com
  db:          redis
  
xml2json:
  object:        true
  reversible:    false
  coerce:        false
  sanitize:      true
  trim:          true
  arrayNotation: false
  
#http://breakdance.io/docs.html#options
#https://www.npmjs.com/package/breakdance-reflinks
markdown:
  condense: true
  one:      true
  # title:    true
  
feed:
  addmeta: true

language:
  isHtml: true
