db:
  provider:           redis
  action:             save
  db:                 0
  id:                 $id
  key:                DEFAULT_KEY

forward:
  tap: false

tap:
  tap: true
  
get:
  # headers:
  accept:             '*/*'
  connection:         keep-alive
  compressed:         true

  method:             get
  follow:             20
  follow_set_cookies: true
  follow_set_referer: true
  follow_keep_method: true

  rejectUnauthorized: false
  parse:              false
  timeout:            0
  limit:              100
  url:                $url

placeholders:         
  url:         example.com
  
xml2json:
  object:        true
  reversible:    false
  coerce:        false
  sanitize:      true
  trim:          true
  arrayNotation: false
