placeholders:
  url:         example.com
  db:          redis
  cache:       cache

db:
  provider:           $db
  action:             save
  db:                 0
  id:                 $id
  key:                DEFAULT_KEY
  return:             key
  elasticsearch:
    #https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html
    connectTimeout:     1
    enableOfflineQueue: true
    keepAlive:          no
    dropBufferSupport:  true
    host: localhost:9200
    log: trace
  redis:
    #https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options
    path:               /tmp/redis.sock

forward:
  tap: false

tap:
  tap: true

get:
  cached:             true
  url:                $url
  cache:              $cache
  parse:              true
  driver:             needle

  needle:

    #https://github.com/tomas/needle#request-options
    parse:              false
    accept:             '*/*'
    compressed:         true
    method:             get
    follow_max:         20
    follow_set_cookies: true
    follow_set_referer: true
    follow_keep_method: true
    rejectUnauthorized: false
    open_timeout:       20000
    read_timeout:       20000

  puppeteer:
    debug: '-puppeteer:*'
    ignoreHTTPSErrors: true
    headless:          true

    # timeout:           3000
    defaultViewport:
      width: 1920
      height: 1080
    args:
     - --app=https://www.google.com/ #Magic
    devtools:          true
    slowMo:            0

    goto:
      waitFor: domcontentloaded


post:
  url:                $url
  method:             post

meta:
  url:                $url

xml2json:
  #https://github.com/buglabs/node-xml2json#options-object-for-tojson
  object:        true
  reversible:    false
  coerce:        false
  sanitize:      true
  trim:          true
  arrayNotation: false

markdown:
  #http://breakdance.io/docs.html#options
  #https://www.npmjs.com/package/breakdance-reflinks
  condense: true
  one:      true
  # title:    true

feed:
  #https://github.com/danmactough/node-feedparser#options
  addmeta: true

language:
  #https://github.com/dachev/node-cld#advanced
  isHtml: true

html:
  # addMetaCharset: true

  encloseBlockText: true
  dropEmptyElements: true
  dropEmptyParas: true
  encloseText: true
  escapeCdata: true
  hideComments: true
  breakBeforeBr: true
  indent: true
  omitOptionalTags: false
  wrap: 0
  clean: false
  showBodyOnly: true
  #not working
  dropFontTags: true
  doctype: omit
  dropProprietaryAttributes: false
