db:
  name:               redis
  action:             save
  db:                 0

request:
  method:             get
  follow:             5
  rejectUnauthorized: false
  compressed:         true
  parse:              false

get:
  method:             get
  follow:             5
  rejectUnauthorized: false
  compressed:         true
  parse:              false

placeholders:
  $q:                 ''
