placeholders:
  url:         example.com
  db:          redis

db:
  provider:           $db
  action:             save
  db:                 0
  id:                 $id
  key:                DEFAULT_KEY
  return:             key
  elasticsearch:
    #https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html
    connectTimeout:     1
    enableOfflineQueue: true
    keepAlive:          no
    dropBufferSupport:  true
    host: localhost:9200
    log: trace
  redis:
    #https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options
    path:               /var/run/redis/sock

forward:
  tap: false

tap:
  tap: true

get:
  cached:             true
  parse:              true
  url:                $url

  #https://github.com/tomas/needle#request-options
  accept:             '*/*'
  compressed:         true
  method:             get
  follow_max:         20
  follow_set_cookies: true
  follow_set_referer: true
  follow_keep_method: true
  rejectUnauthorized: false
  open_timeout:       20000
  read_timeout:       20000

post:
  url:                $url
  method: post

meta:
  url:                $url

xml2json:
  #https://github.com/buglabs/node-xml2json#options-object-for-tojson
  object:        true
  reversible:    false
  coerce:        false
  sanitize:      true
  trim:          true
  arrayNotation: false

markdown:
  #http://breakdance.io/docs.html#options
  #https://www.npmjs.com/package/breakdance-reflinks
  condense: true
  one:      true
  # title:    true

feed:
  #https://github.com/danmactough/node-feedparser#options
  addmeta: true

language:
  #https://github.com/dachev/node-cld#advanced
  isHtml: true

html:
  # addMetaCharset: true
  encloseBlockText: true
  encloseText: true
  escapeCdata: true
  hideComments: true
  breakBeforeBr: true
  indent: true
  omitOptionalTags: true
  wrap: 150
  clean: false
  doctype: omit
