db:
  provider:           redis
  action:             save
  db:                 0
  pre:                json
  post:               json
  id:                 $id
  key:                DEFAULT_KEY

request:
  method:             get
  follow:             5
  rejectUnauthorized: false
  open_timeout:       5000
  compressed:         true
  parse:              false
  limit:              10

forward:
  tap: false

tap:
  tap: true
  
get:
  method:             get
  follow:             5
  rejectUnauthorized: false
  compressed:         true
  parse:              false
  limit:              10

placeholders:
  $q:                 ''
  
xml2json:
  object:        true
  reversible:    false
  coerce:        false
  sanitize:      true
  trim:          true
  arrayNotation: false
